name: .NET Core
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish  -c Release --self-contained -r win-x64
      
    - name: Build Artifact
      uses: actions/upload-artifact@v2
      with:
          name: webscraper
          path: /home/runner/work/Webscraper-WarreHofmans/Webscraper-WarreHofmans/bin/Release/netcoreapp3.1/win-x64/publish/
