name: .NET Core
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
    - name: Publish
      run: dotnet publish  -r win-x64
      
    - name: Upload WebApp1 Build Artifact
      uses: actions/upload-artifact@v2
      with:
          name: WebApp1
          path: /home/runner/work/webscraper/webscraper/bin/Debug/netcoreapp3.1/publish/
