name: .NET Core
on:
  push:
    branches: [ experimental ]
  pull_request:
    branches: [ experimental ]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.101
 
    - name: Install dependencies
      run: dotnet restore
      
    - name: Build
      run: dotnet build --configuration Release --no-restore
      
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
    - name: Publish
      run: dotnet publish  
      
    - name: Build Artifact
      uses: actions/upload-artifact@v2
      with:
          name: ExperimentalWebscraper
          path: /home/runner/work/webscraper/webscraper/bin/Debug/netcoreapp3.14/publish/
